language: cpp

git:
  depth: 10

jobs:
  include:
  - name: macOS
    os: osx
    cache:
      directories:
      - $HOME/SFML_OSX
    script:
      - chmod +x tests/travis_osx.sh
      - tests/travis_osx.sh
